#theme: https://github.com/sharadcodes/jekyll-theme-serial-programmer

title: Liucreator's Blog
markdown: kramdown
url: "https://liucreator.github.io/"
baseurl: "/jekyll-theme-serial-programmer"

# for atom feed
author:
  name: liucreator
  email: liucreator@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
