baseURL = "https://liucreator.github.io/"
title = "LEDIS' Blog"
paginate = 5
theme = "PaperMod"
publishdir = "./docs"
copyright = "是我的～"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ledis' blog"
description = "This is LEDIS' Blog; 这是小刘的博客"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "liucreator"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  #safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "主页"
  icon = "/profile.jpg"
  iconHeight = 32

  [params.profileMode]
  enabled = true
  title = "LEDIS的博客"
  subtitle = "施工中～"
  imageUrl = "/profile.jpg"
  imageWidth = 128
  imageHeight = 128
  imageTitle = "profile pic"

    [[params.profileMode.buttons]]
    name = "随笔"
    url = "post"

    [[params.profileMode.buttons]]
    name = "标签"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hey~"
  Content = "Welcome to my blog!"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/ledisthebest"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/<path_to_repo>/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "categories"
#name = "分类"
#url = "/categories/"
#weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "陈年旧事"
url = "/archives/"
weight = 30

[[menu.main]]
identifier = "home"
name = "liucreator.github.io"
url = "https://liucreator.github.io"
weight = 40
